# Generated by Django 3.0.2 on 2020-01-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20, verbose_name='Rozszerzenie pliku')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20, verbose_name='Typ aplikacji')),
            ],
        ),
        migrations.CreateModel(
            name='Animations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nazwa')),
                ('author', models.CharField(max_length=30, verbose_name='Autor kodu')),
                ('date', models.DateTimeField(verbose_name='Data dodania')),
                ('code', models.CharField(max_length=10000, unique=True, verbose_name='Kod')),
                ('approved', models.BooleanField(default=False, verbose_name='Status zatwierdzenia')),
                ('date_approved', models.DateField(verbose_name='Data zatwierdzenia')),
                ('id_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Led.Lang')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Led.Type')),
            ],
        ),
    ]
