# Generated by Django 3.0.2 on 2020-01-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animations',
            new_name='Animation',
        ),
    ]
