# Generated by Django 3.0.2 on 2020-01-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0004_auto_20200120_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
    ]
