# Generated by Django 3.0.3 on 2020-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0005_auto_20200120_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='code',
            field=models.TextField(max_length=10000, verbose_name='Kod'),
        ),
    ]
