# Generated by Django 3.0.3 on 2020-02-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0006_auto_20200221_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Opis'),
        ),
    ]
