# Generated by Django 3.0.3 on 2020-02-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Led', '0007_animation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_animation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Led.Animation')),
            ],
        ),
    ]
